### ISSUE TITLE
is this repo still works ? 

### ISSUE THREAD

**Issue by AJ1062910** [dsebastien/office-plugins-nx-workspace-template#1]
I try the repo but after the npm start and when we opened it on office word we can load the plugin but it is empty, word seem to do not recognize angular, only basic html on index.html 
@dsebastien dsebastie
do you know why ?

**Comment by AJ1062910** [comment]
up
@dsebastien

**Comment by dsebastien** [comment]
Hello @AJ1062910,

Unfortunately, I don't have time to maintain this repository anymore. I will accept all contributions!
